#!/bin/bash

# File to create or edit
> $(HOME)/etc/haproxy/haproxy.cfg
CONFIG_FILE="$(HOME)/etc/haproxy/haproxy.cfg"

FRONTEND_IP=$(jq '.frontend.ip' takeover.JSON)
FRONTEND_PORT=$(jq '.frontend.port' takeover.JSON)
NUM_CONTROLLERS=$(jq '.controllers.number' takeover.JSON)

# Generate frontend section
cat <<EOF >> $CONFIG_FILE
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log global
	mode tcp
	option tcplog
	option dontlognull
	timeout connect 5000
	timeout client 50000
	timeout server 50000

frontend proxy_frontend
	bind $FRONTEND_IP:$FRONTEND_PORT
	default_backend controllers

EOF

# Generate backend section
cat <<EOF >> $CONFIG_FILE
backend controllers
	mode tcp
	balance roundrobin
	option tcp-check
	tcp-check connect port 6633
EOF

# Add controller servers 
for ((i=1;i<=$NUM_CONTROLLERS;i++)); do
if [ $i == 1 ]
then
CONTROLLER_IP=$(jq ".controllers.controller$i.ip" takeover.JSON)
PORT=$(jq ".controllers.controller$i.port" takeover.JSON)
cat <<EOF >> $CONFIG_FILE
	server ryu_controller$i $CONTROLLER_IP:$PORT check inter 3000
EOF
else
CONTROLLER_IP=$(jq ".controllers.controller$i.ip" takeover.JSON)
PORT=$(jq ".controllers.controller$i.port" takeover.JSON)
cat <<EOF >> $CONFIG_FILE
	server ryu_controller$i $CONTROLLER_IP:$PORT check inter 3000 backup
EOF
fi
done

